### ISSUE TITLE
No connection adapters

### ISSUE THREAD

**Issue by teshiburu** [Hellowlol/bw_plex#10]
Ok - so i ditched running this on windows for the moment :P got it on ubuntu at the moment but getting this error 

requests.exceptions.InvalidSchema: No connection adapters were found for '192.168.1.220:32400/?X-Plex-Token=

**Comment by teshiburu** [comment]
OKey dokey fixed that error plexapi was not up to date, this time i get another error message. 

Y:\bw_plex-master>python plex_jump.py update_all_themes
2018-01-13 07:57:14,540 :: __main__ :: INFO :: Loading existing files in db
Traceback (most recent call last):
  File "plex_jump.py", line 56, in <module>
    HT = HashTable(FP_HASHES)
  File "Y:\bw_plex-master\audfprint\hash_table.py", line 51, in __init__
    self.load(filename)
  File "Y:\bw_plex-master\audfprint\hash_table.py", line 203, in load
    self.load_pkl(name)
  File "Y:\bw_plex-master\audfprint\hash_table.py", line 217, in load_pkl
    temp = pickle.load(f)
EOFError

Any ideas?

**Comment by Hellowlol** [comment]
I have made some changes in order to get better themes (and as a result better matching). But I haven’t had time to test it so everything might be broken :/

**Comment by teshiburu** [comment]
@Hellowlol hehe - fair enough, ive not yet had it skip one intro, i didnt run the hashes command as it kept bugging out on other tracks - i've watched one show all weekend. 

Kinda expected to see one skip by now, so possible it is all broken :P

**Comment by teshiburu** [comment]
In reference to the above - i just see this in the terminal screens for "plex_jump.py watch"

```
2018-01-14 15:41:15,611 :: urllib3.connectionpool :: DEBUG :: Resetting dropped connection: 192.168.1.220
2018-01-14 15:41:15,628 :: urllib3.connectionpool :: DEBUG :: http://192.168.1.220:32400 "GET /library/metadata/7247?X-Plex-Token=XXXXXX HTTP/1.1" 200 1258
2018-01-14 16:02:46,521 :: urllib3.connectionpool :: DEBUG :: Resetting dropped connection: 192.168.1.220
2018-01-14 16:02:46,561 :: urllib3.connectionpool :: DEBUG :: http://192.168.1.220:32400 "GET /library/metadata/439545?X-Plex-Token=XXXXXX HTTP/1.1" 200 3800
2018-01-14 16:32:10,965 :: urllib3.connectionpool :: DEBUG :: Resetting dropped connection: 192.168.1.220
2018-01-14 16:32:11,010 :: urllib3.connectionpool :: DEBUG :: http://192.168.1.220:32400 "GET /library/metadata/7248?X-Plex-Token=XXXXXX HTTP/1.1" 200 1264
2018-01-14 17:16:20,645 :: urllib3.connectionpool :: DEBUG :: Resetting dropped connection: 192.168.1.220
2018-01-14 17:16:20,658 :: urllib3.connectionpool :: DEBUG :: http://192.168.1.220:32400 "GET /library/metadata/7249?X-Plex-Token=XXXXXX HTTP/1.1" 200 1264

```

Doesnt seem to be much else going on there.

**Comment by Hellowlol** [comment]
What show was you testing?

**Comment by teshiburu** [comment]
NCIS and friends

It has worked so far on two and a half men and scandal

**Comment by Hellowlol** [comment]
OK, if you want to see what is processes so far you can open the db in a tool like http://sqlitebrowser.org/.  See in the start and end column. If the tool find the theme in the video it should be a positiv number, if not it should be -1

**Comment by teshiburu** [comment]
OK - there is nothing in the media.db file any further ideas lol!

**Comment by Hellowlol** [comment]
Git clone again.

delete db and hashes.pklz
plex_jump.py process -name monk
Select the episode your want to process. 
Start playing what evr you want to watch and see if it does anything.

**Comment by teshiburu** [comment]
Deleted the files i had from before and reinstalled with pip, getting this error now? 

`administrator@VirginSpeedTest:~/bw_plex/bw_plex$ python plex.py process -name NCIS
2018-01-21 16:11:10,849 :: plex :: INFO :: Loading existing files in db
Read fprints for 0 files ( 0 hashes) from /home/administrator/.config/bw_plex/hashes.pklz (0.00% dropped)
2018-01-21 16:12:26,509 :: plex :: DEBUG :: Loading themes
Traceback (most recent call last):
  File "plex.py", line 529, in <module>
    cli()
  File "/home/administrator/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/administrator/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/administrator/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/administrator/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/administrator/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "plex.py", line 206, in process
    shows = find_all_shows()
  File "plex.py", line 82, in find_all_shows
    for section in PMS.library.sections():
AttributeError: 'NoneType' object has no attribute 'library'
`

**Comment by Hellowlol** [comment]
I think you need to edit the config file in home folder .config bw_plex.

**Comment by teshiburu** [comment]
ok - fixed that and it worked fine, ran plex.py watch and it worked fine. 

so then i went to run it in screen and now i get this error inside and outside of screen 

`administrator@VirginSpeedTest:~/bw_plex/bw_plex$ python plex.py watch
2018-01-22 19:57:33,906 :: plex :: INFO :: Loading existing files in db
Traceback (most recent call last):
  File "plex.py", line 41, in <module>
    HT = HashTable(FP_HASHES)
  File "/home/administrator/bw_plex/bw_plex/audfprint/hash_table.py", line 51, in __init__
    self.load(filename)
  File "/home/administrator/bw_plex/bw_plex/audfprint/hash_table.py", line 203, in load
    self.load_pkl(name)
  File "/home/administrator/bw_plex/bw_plex/audfprint/hash_table.py", line 217, in load_pkl
    temp = pickle.load(f)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x702e7365 != 0x0L
administrator@VirginSpeedTest:~/bw_plex/bw_plex$
`

**Comment by Hellowlol** [comment]
Delete hashes pklz and try again.

**Comment by teshiburu** [comment]
Cool - ill give that a go, 

Seems my install may have got messy, seems some major changes your end since i started testing this, 

time to setup a VM just for bw_plex :)

**Comment by Hellowlol** [comment]
Just install it with pip install bw_plex

**Comment by teshiburu** [comment]
Seems to be working well for a few shows now. 

Only small bug bear is where the intro theme is after a  minute or so of starting i miss the opening scene

**Comment by Hellowlol** [comment]
Thats intended atm. In a later version i will add support for different methods to handle this.
