### ISSUE TITLE
check_db should have a specific video option

### ISSUE THREAD

**Issue by jpartain89** [Hellowlol/bw_plex#101]
When running `check_db` command, its been defaulting to the first movie in my database, which gets the times returned as "NONE" even though its been processed... This none error causes it to fail, of course...

```
2019-09-12 23:47:32,265 :: bw_plex :: INFO :: __init__.py:172 :: Using bw_plex version 0.1.1.dev58+gad6d85a
2019-09-12 23:47:32,266 :: bw_plex :: INFO :: __init__.py:173 :: default folder set to /Users/jpartain89/.config/bw_plex
2019-09-12 23:47:33,504 :: bw_plex :: INFO :: plex.py:1382 :: Added signal handler.
2019-09-12 23:47:33,529 :: bw_plex :: DEBUG :: misc.py:64 :: Getting server Justin's iMac

1 Justin’s AppleTV
0 Firefox

Select what client to use: 1

Checking 12 Angry Men
theme_start None theme_end None ffmpeg_end 22.189
*--------------------------------------------------------------------------------*

Found theme_start at None None theme_end None None
Traceback (most recent call last):
  File "/usr/local/bin/bw_plex", line 11, in <module>
    load_entry_point('bw-plex', 'console_scripts', 'bw_plex')()
  File "/usr/local/Cellar/python/3.7.4_1/bin/src/bw-plex/bw_plex/cli.py", line 24, in fake_main
    real_main()
  File "/usr/local/Cellar/python/3.7.4_1/bin/src/bw-plex/bw_plex/plex.py", line 1393, in real_main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.4_1/bin/src/bw-plex/bw_plex/plex.py", line 379, in check_db
    client.playMedia(media, offset=item.theme_start * 1000)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

And I just confirmed this happens for either client listed.

**Comment by Hellowlol** [comment]
Should be fixed now.
