### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Inrego** [Hellowlol/bw_plex#119]
After using bw_plex with docker, I decided to try just installing it on my Ubuntu machine instead of docker. I used the install script as per the docs, but when trying to run it, I received this error whenever trying to run bw_plex:

```
Traceback (most recent call last):
  File "/usr/local/bin/bw_plex", line 11, in <module>
    load_entry_point('bw-plex', 'console_scripts', 'bw_plex')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/bw_plex/src/bw-plex/bw_plex/__init__.py", line 8, in <module>
    from plexapi.compat import string_type
  File "/usr/local/lib/python2.7/dist-packages/plexapi/__init__.py", line 6, in <module>
    from plexapi.config import PlexConfig, reset_base_headers
  File "/usr/local/lib/python2.7/dist-packages/plexapi/config.py", line 4, in <module>
    from plexapi.compat import ConfigParser
  File "/usr/local/lib/python2.7/dist-packages/plexapi/compat.py", line 50, in <module>
    from mock import patch, MagicMock
ImportError: No module named mock
```

I then ran `pip install mock`, and now I'm getting this:
```
Traceback (most recent call last):
  File "/usr/local/bin/bw_plex", line 11, in <module>
    load_entry_point('bw-plex', 'console_scripts', 'bw_plex')()
  File "/opt/bw_plex/src/src/bw-plex/bw_plex/cli.py", line 21, in fake_main
    bw_plex.init(folder=default_folder, debug=debug, config=config)
  File "/opt/bw_plex/src/src/bw-plex/bw_plex/__init__.py", line 127, in init
    os.makedirs(DEFAULT_FOLDER, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```

As far as I can gather, this error comes because python2 is used instead of python3. Here are my installed versions:

```
python -V
Python 2.7.16
python3 -V
Python 3.7.3
```

Got any ideas?

**Comment by Hellowlol** [comment]
Your using python2. Try 🐍 3

**Comment by Inrego** [comment]
How do I "use" python 3? I have both installed, and I'm just running bw_plex

**Comment by Hellowlol** [comment]
I think you can call it manually.

python3 -m bw_plex watch

**Comment by Hellowlol** [comment]
Closing this for inactivity.
