### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by justlookingaround12** [Hellowlol/bw_plex#13]
Hey guys sorry for the noob question, but how should i install and use this? i've installed it through pip but not quite sure what to do next. 
Also, is it possible for it to in any way 'hurt' my server?

**Comment by justlookingaround12** [comment]
Alright so now i run it with bwplex (ps in your usage it says bw_plex, so either what im doing is wrong or that needs to be fixed) but i end up with error:
cElementTree.ParseError: mismatched tag: line 35, column 2
and i have filled up the config file correctly i believe

**Comment by Hellowlol** [comment]
Your using a old version. I havnt release a new version to pypi yet.
1. git clone this repo.
2. Edit the config file
3. Start the program using bw_plex watch

**Comment by justlookingaround12** [comment]
I see, just did that, should i edit config.py?

**Comment by Hellowlol** [comment]
No edit the config ini file create in your homefolder/.config/bw_plex

**Comment by justlookingaround12** [comment]
So i tried running it without filling in the config file just to see, i get a command not found error

**Comment by Hellowlol** [comment]
Whats the traceback?

**Comment by justlookingaround12** [comment]
when i cloned it, nothing was created in my .config directory. Also, when i run bw_plex i just get "bw_plex: command not found"

**Comment by Hellowlol** [comment]
Oh. I forgot one step. This should be step 3: ‘’’pip install -e .’’’

**Comment by justlookingaround12** [comment]
so i did the following:
1. git clone the app
2. run "pip install -e"
     here i get error -e option requires an argument 
3. there is no config.ini file..

**Comment by Hellowlol** [comment]
it need the dot: `pip install -e .` Btw i updated the install instructions i gave.

**Comment by justlookingaround12** [comment]
Thanks that worked. However I'm still getting the same error. After filling in the config file and running with "bw_plex watch"
i get:
  File "/home/myplex/.local/lib/python2.7/site-packages/plexapi/server.py", line 347, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "<string>", line 124, in XML
cElementTree.ParseError: mismatched tag: line 35, column 2

**Comment by Hellowlol** [comment]
It complains because the XML response from PMS is malformed. I have no idea what it fails on. You can try to comment out https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/__init__.py#L53-L55 to see what urls it tries to load.

**Comment by justlookingaround12** [comment]
hmm so all i get after commenting them out is:
Traceback (most recent call last):
  File "/home/myplex/.local/bin/bw_plex", line 9, in <module>
    load_entry_point('bw-plex', 'console_scripts', 'bw_plex')()
  File "/home/myplex/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/myplex/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/myplex/.local/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/myplex/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/myplex/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/myplex/.local/lib/python2.7/site-packages/bw_plex/bw_plex/plex.py", line 165, in cli
    servername=servername)
  File "/home/myplex/.local/lib/python2.7/site-packages/bw_plex/bw_plex/misc.py", line 31, in get_pms
    PMS = PlexServer(url, token)
  File "/home/myplex/.local/lib/python2.7/site-packages/plexapi/server.py", line 101, in __init__
    data = self.query(self.key, timeout=timeout)
  File "/home/myplex/.local/lib/python2.7/site-packages/plexapi/server.py", line 347, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "<string>", line 124, in XML
cElementTree.ParseError: mismatched tag: line 35, column 2
