### ISSUE TITLE
Aborted during hashtable/db creation.

### ISSUE THREAD

**Issue by Velkas** [Hellowlol/bw_plex#140]
latest bw_plex on Windows 10 v2004 - fresh install
Latest plex server on same machine.
Plex web browser on same machine.

Command used:
> bw_plex -d -c "\<path\>\config.ini" watch

Log:
> 2020-10-05 15:00:42,805 :: bw_plex :: INFO :: __init__.py:168 :: Using bw_plex version 0.1.1.dev89+g98269f7
2020-10-05 15:00:42,806 :: bw_plex :: INFO :: __init__.py:169 :: default folder set to \<path\>
2020-10-05 15:00:42,806 :: bw_plex :: INFO :: __init__.py:183 :: Log is not sanitized!
2020-10-05 15:00:43,383 :: urllib3.connectionpool :: DEBUG :: connectionpool.py:230 :: Starting new HTTP connection (1): 127.0.0.1:32400
2020-10-05 15:00:43,386 :: urllib3.connectionpool :: DEBUG :: connectionpool.py:442 :: http://127.0.0.1:32400 "GET / HTTP/1.1" 200 2393
2020-10-05 15:00:43,387 :: bw_plex :: DEBUG :: misc.py:64 :: Getting server Arvus
2020-10-05 15:00:43,388 :: bw_plex :: DEBUG :: misc.py:572 :: Getting hashtable
2020-10-05 15:00:43,507 :: bw_plex :: INFO :: misc.py:663 :: Creating new hashtable db
2020-10-05 15:00:43,508 :: bw_plex :: DEBUG :: misc.py:594 :: Saving HashTable

Console Output:
> 2020-10-05 15:00:42,805 :: bw_plex :: INFO :: __init__.py:168 :: Using bw_plex version 0.1.1.dev89+g98269f7
2020-10-05 15:00:42,806 :: bw_plex :: INFO :: __init__.py:169 :: default folder set to \<path\>
2020-10-05 15:00:42,806 :: bw_plex :: INFO :: __init__.py:183 :: Log is not sanitized!
2020-10-05 15:00:43,383 :: urllib3.connectionpool :: DEBUG :: connectionpool.py:230 :: Starting new HTTP connection (1): 127.0.0.1:32400
2020-10-05 15:00:43,386 :: urllib3.connectionpool :: DEBUG :: connectionpool.py:442 :: http://127.0.0.1:32400 "GET / HTTP/1.1" 200 2393
2020-10-05 15:00:43,387 :: bw_plex :: DEBUG :: misc.py:64 :: Getting server Arvus
2020-10-05 15:00:43,388 :: bw_plex :: DEBUG :: misc.py:572 :: Getting hashtable
2020-10-05 15:00:43,507 :: bw_plex :: INFO :: misc.py:663 :: Creating new hashtable db
2020-10-05 15:00:43,508 :: bw_plex :: DEBUG :: misc.py:594 :: Saving HashTable
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\bw_plex-script.py", line 33, in <module>
    sys.exit(load_entry_point('bw-plex', 'console_scripts', 'bw_plex')())
  File "c:\users\\<user\>\src\bw-plex\bw_plex\cli.py", line 24, in fake_main
    real_main()
  File "c:\users\\<user\>\src\bw-plex\bw_plex\plex.py", line 1401, in real_main
    cli()
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\\<user\>\src\bw-plex\bw_plex\plex.py", line 1305, in watch
    HT = get_hashtable()
  File "c:\users\\<user\>\src\bw-plex\bw_plex\misc.py", line 666, in get_hashtable
    HT.save(FP_HASHES)
  File "c:\users\\<user\>\src\bw-plex\bw_plex\misc.py", line 612, in save
    pickle.dump(self, f, pickle.HIGHEST_PROTOCOL)
MemoryError

Because the hash/db file wasn't saved correctly, I get subsequent Aborted launches, when I remove those files I get this same error so it's at least consistent. Let me know if there's additional info I can provide that might help.

**Comment by Hellowlol** [comment]
Can i have the entire log? I dont understand why you should get a memory error on the start up unless the file is big. How much memory have you installed? Is this a 64 bit Python install?

**Comment by Velkas** [comment]
That is the full log, I deleted everything cleaned out. Clones the repo and installed via instructions. This was first startup after I filled out my config file.

That said, it looks like this is using the 32 bit version of python. I'm going to try switching to 64 bit, I somehow overlooked that trying to diagnose the issue. I'll report back.

**Comment by Velkas** [comment]
Yup, that did the trick. Currently up and running. Thanks, I appreciate the quick response from you!
