### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by megarage** [Hellowlol/bw_plex#152]
I am having this issue since i install it.
I have all configured and all seems in order but i keep getting the following 

C:\Users\Oracle>bw_plex watch
2022-05-02 12:49:08,047 :: bw_plex :: INFO :: __init__.py:168 :: Using bw_plex version 0.1.1.dev95+g86768d6
2022-05-02 12:49:08,047 :: bw_plex :: INFO :: __init__.py:169 :: default folder set to C:\Users\Oracle/.config/bw_plex
2022-05-02 12:49:08,699 :: bw_plex :: DEBUG :: misc.py:64 :: Getting server Oracle
2022-05-02 12:49:08,700 :: bw_plex :: DEBUG :: misc.py:572 :: Getting hashtable
2022-05-02 12:49:08,836 :: bw_plex :: INFO :: misc.py:663 :: Creating new hashtable db
2022-05-02 12:49:08,837 :: bw_plex :: DEBUG :: misc.py:594 :: Saving HashTable
2022-05-02 12:49:15,079 :: bw_plex :: DEBUG :: misc.py:587 :: Files in the hashtable
Watching for media on Oracle
2022-05-02 12:49:15,091 :: bw_plex :: DEBUG :: plex.py:1318 :: ws event Ready(response=<response HTTP/1.1 101 Switching Protocols>, protocol=None, extensions=set())
2022-05-02 12:49:24,921 :: bw_plex :: DEBUG :: plex.py:1238 :: Failed to find ratingkey 60986 in the db
2022-05-02 12:49:24,949 :: bw_plex :: DEBUG :: plex.py:1098 :: Found Family Guy - s20e17 - All About Alana
2022-05-02 12:49:24,950 :: bw_plex :: DEBUG :: plex.py:1103 :: Download the first 10 minutes of Family Guy - s20e17 - All About Alana as .wav
2022-05-02 12:49:24,951 :: bw_plex :: DEBUG :: plex.py:886 :: Checking if we can reach Family Guy - s20e17 - All About Alana directly
2022-05-02 12:49:24,952 :: bw_plex :: DEBUG :: plex.py:896 :: Found F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv directly
2022-05-02 12:49:24,955 :: bw_plex :: DEBUG :: audio.py:45 :: calling ffmpeg with ffmpeg -i "F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv" -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le C:\Users\Oracle\AppData\Local\Temp\offset_adsas4ho.wav
2022-05-02 12:49:24,984 :: bw_plex :: ERROR :: plex.py:89 :: There was an exception in task
Traceback (most recent call last):
  File "c:\windows\system32\src\bw-plex\bw_plex\plex.py", line 84, in inner
    return func(*args)
  File "c:\windows\system32\src\bw-plex\bw_plex\plex.py", line 1104, in task
    vid = convert_and_trim(check_file_access(media), fs=11025,
  File "c:\windows\system32\src\bw-plex\bw_plex\audio.py", line 50, in convert_and_trim
    psox = subprocess.Popen(cmd, stderr=subprocess.PIPE)
  File "C:\Users\Oracle\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Oracle\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

No matter what episode I choose.
I have the FFmpeg installed 
64GB of ddr3 ram 
windows 10 64
Python 64 
Intel Xeon X5690 3.47ghz
plex version 4.76.1
and i have the most recent version of BW_plex installed via git

Can i get a hand here please? thank you up front for your time and help

**Comment by Hellowlol** [comment]
I haven't been using bw_plex for a very long time after plex added native support for it. Try executing the command using cmd in `ffmpeg with ffmpeg -i "F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv" -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le`

**Comment by megarage** [comment]
m doing something wrong i get an error message saying 

C:\Users\Oracle>ffmpeg -i "F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv" -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

**"I haven't been using bw_plex for a very long time after plex added native support for it."**
yeah, i know plex has it now but you need a plex pass and is a bit pricy for the little features they give.

**Comment by megarage** [comment]
or if i do 
C:\Users\Oracle>

C:\Users\Oracle>bw_plex ffmpeg -i "F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv" -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le
2022-05-02 14:35:30,407 :: bw_plex :: INFO :: __init__.py:168 :: Using bw_plex version 0.1.1.dev95+g86768d6
2022-05-02 14:35:30,409 :: bw_plex :: INFO :: __init__.py:169 :: default folder set to C:\Users\Oracle/.config/bw_plex
Usage: bw_plex [OPTIONS] COMMAND [ARGS]...
Try 'bw_plex --help' for help.

Error: No such command 'ffmpeg'.

C:\Users\Oracle>bw_plex ffmpeg with ffmpeg -i "F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv" -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le
2022-05-02 14:36:44,536 :: bw_plex :: INFO :: __init__.py:168 :: Using bw_plex version 0.1.1.dev95+g86768d6
2022-05-02 14:36:44,536 :: bw_plex :: INFO :: __init__.py:169 :: default folder set to C:\Users\Oracle/.config/bw_plex
Usage: bw_plex [OPTIONS] COMMAND [ARGS]...
Try 'bw_plex --help' for help.

Error: No such command 'ffmpeg'.
 i get that

**Comment by Hellowlol** [comment]
Well, that means that the FFmpeg is not in the path where cmd can find it. You need to add it to the path https://www.computerhope.com/issues/ch000549.htm

**Comment by Hellowlol** [comment]
I copypasted the some of the text string, the correct one is ```ffmpeg -i "F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv" -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le```

**Comment by megarage** [comment]
This is what i get now

C:\Users\Oracle>ffmpeg -i "F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv" -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le
ffmpeg version 2022-05-02-git-40f2ea971f-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 27.100 / 59. 27.100
  libavformat    59. 23.100 / 59. 23.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 37.100 /  8. 37.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Trailing option(s) found in the command: may be ignored.
Input #0, matroska,webm, from 'F:\Episodes\Family guy\Season 20\Family Guy - S20E17 - All About Alana.mkv':
  Metadata:
    encoder         : libebml v1.4.0 + libmatroska v1.6.1
  Duration: 00:21:38.03, start: 0.000000, bitrate: 4154 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
  Stream #0:1(eng): Audio: aac (HE-AAC), 48000 Hz, stereo, fltp (default)
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English
At least one output file must be specified

C:\Users\Oracle>

**Comment by Hellowlol** [comment]
It is pretty clear what's missing, you need to add the out file as well. F.x something.wav. Anyway, now that FFmpeg is working you could try running bw_plex again.

**Comment by megarage** [comment]
Now it seems to be doing something in the background, there is no more error like the reported initial one. but still is not skipping the intro or giving me a button to skip into. but I do not see any error either.

**Comment by megarage** [comment]
It is working now, this is how i fixed it.
I needed to download the FFmpeg manually directly to my C: then add it to the path like instructed by the link you sent me. restart the pc and then start with bw_plex watch.

the first time i open a new serie he examines it and adds it to the library and the next time i see the same series it skips the intro
