### ISSUE TITLE
timestamp out of range for platform localtime()/gmtime() function

### ISSUE THREAD

**Issue by PearsonFlyer** [Hellowlol/bw_plex#65]
On Windows 10 again, when I try to process a show, I get this error every time.

```
>bw_plex process -n Luther

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\bw_plex.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\bw_plex\plex.py", line 1048, in real_main
    cli()
  File "c:\python27\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\bw_plex\plex.py", line 378, in process
    medias = find_all_movies_shows()
  File "c:\python27\lib\site-packages\bw_plex\plex.py", line 73, in find_all_movies_shows
    all_shows += section.all()
  File "c:\python27\lib\site-packages\plexapi\library.py", line 383, in all
    return self.fetchItems(key, **kwargs)
  File "c:\python27\lib\site-packages\plexapi\base.py", line 148, in fetchItems
    items = self.findItems(data, cls, ekey, **kwargs)
  File "c:\python27\lib\site-packages\plexapi\base.py", line 169, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "c:\python27\lib\site-packages\plexapi\base.py", line 87, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "c:\python27\lib\site-packages\plexapi\base.py", line 79, in _buildItem
    return ecls(self._server, elem, initpath)
  File "c:\python27\lib\site-packages\plexapi\base.py", line 48, in __init__
    self._loadData(data)
  File "c:\python27\lib\site-packages\plexapi\video.py", line 290, in _loadData
    Video._loadData(self, data)
  File "c:\python27\lib\site-packages\plexapi\video.py", line 33, in _loadData
    self.addedAt = utils.toDatetime(data.attrib.get('addedAt'))
  File "c:\python27\lib\site-packages\plexapi\utils.py", line 181, in toDatetime
    value = datetime.fromtimestamp(int(value))
ValueError: timestamp out of range for platform localtime()/gmtime() function
```
Please let me know if you need any further info.  Thanks!

**Comment by Hellowlol** [comment]
Can you check the value the xml info about that episode? I wondering what the value of addedAt is

**Comment by Hellowlol** [comment]
I have sent a pr to plexapi. Lets hope that solves the issue.

**Comment by Hellowlol** [comment]
You can try to install plexapi from GitHub. I think my pr should fix your issue

**Comment by PearsonFlyer** [comment]
I installed the updated .py files over mine.  When I fired up bw_plex
watch, I got a bunch of errors, but it ended with this:

File "c:\python27\lib\site-packages\plexapi\utils.py", line 183, in
toDatetime
    value = datetime.datetime(1970, 1, 1) +
datetime.fromtimestamp(milliseconds=value)
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

**Comment by Hellowlol** [comment]
Shit it didnt fix what i had intended. I have to come back to this later.

**Comment by Hellowlol** [comment]
if fix the error i introduced, just grab a fresh file.

**Comment by Hellowlol** [comment]
what os are you using and what was the value in the xml?

**Comment by PearsonFlyer** [comment]
Okay, I grabbed the latest plexapi, and that seems to have resolved the
issue. It's no longer throwing that error, and actually starts to grab
stuff for things people are watching.  Thank you!
