### ISSUE TITLE
Error in credits.py

### ISSUE THREAD

**Issue by bencmeyer** [Hellowlol/bw_plex#73]
Running inside a docker on unraid;

2019-02-10 22:48:01,675 :: bw_plex :: ERROR :: credits.py:353 :: There was a error in find_credits

Traceback (most recent call last):
File "/app/bw_plex/bw_plex/credits.py", line 333, in find_credits
step=step, frame_range=frame_range)):
File "/app/bw_plex/bw_plex/credits.py", line 144, in video_frame_by_frame
cv2.destroyAllWindows()
cv2.error: OpenCV(4.0.0) /io/opencv/modules/highgui/src/window.cpp:619: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

2019-02-10 22:48:01,701 :: bw_plex :: DEBUG :: plex.py:199 :: Added Star.Trek:.Discovery.s02e04 to media.db
2019-02-10 22:48:01,716 :: bw_plex :: DEBUG :: plex.py:899 :: Deleted /tmp/offset_sbsfyy4_.wav
2019-02-10 22:48:01,716 :: bw_plex :: DEBUG :: misc.py:89 :: Check if we can find the next media item.
2019-02-10 22:48:01,779 :: bw_plex :: DEBUG :: misc.py:100 :: Failed to find the next media item of Star Trek: Discovery

2019-02-10 22:48:01,675 :: bw_plex :: ERROR :: credits.py:353 :: There was a error in find_credits

Traceback (most recent call last):
File "/app/bw_plex/bw_plex/credits.py", line 333, in find_credits
step=step, frame_range=frame_range)):
File "/app/bw_plex/bw_plex/credits.py", line 144, in video_frame_by_frame
cv2.destroyAllWindows()
cv2.error: OpenCV(4.0.0) /io/opencv/modules/highgui/src/window.cpp:619: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**Comment by Hellowlol** [comment]
Thanks. This seems to be issue with opencv4. I’ll fix this in a couple of days. I don’t think we need to call that command anyway.

**Comment by Hellowlol** [comment]
This should be fixed with the latest commit.
