### ISSUE TITLE
docker container crashes immediately

### ISSUE THREAD

**Issue by gajewsk2** [Hellowlol/bw_plex#79]
Hey there, I'm on docker on windows 10 giving me issues when I run the container. I'm really not sure how to get started running commands for the container. What steps do you need to take to get it running after `docker run -it hellowlol/bw_plex`
```

C:\Users\micah>docker run -it hellowlol/bw_plex
2019-03-24 02:18:42,916 :: bw_plex :: INFO :: __init__.py:161 :: default folder set to /config
2019-03-24 02:18:44,215 :: bw_plex :: DEBUG :: misc.py:630 :: Getting hashtable
2019-03-24 02:18:44,463 :: bw_plex :: INFO :: misc.py:721 :: Creating new hashtable db
2019-03-24 02:18:44,467 :: bw_plex :: DEBUG :: misc.py:652 :: Saving HashTable
2019-03-24 02:19:09,510 :: bw_plex :: DEBUG :: misc.py:645 :: Files in the hashtable
Traceback (most recent call last):
  File "/usr/local/bin/bw_plex", line 11, in <module>
    load_entry_point('bw-plex', 'console_scripts', 'bw_plex')()
  File "/app/bw_plex/bw_plex/cli.py", line 24, in fake_main
    real_main()
  File "/app/bw_plex/bw_plex/plex.py", line 1280, in real_main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/bw_plex/bw_plex/plex.py", line 1201, in watch
    click.echo('Watching for media on %s' % PMS.friendlyName)
AttributeError: 'NoneType' object has no attribute 'friendlyName'
```

**Comment by gajewsk2** [comment]
`>docker run -it hellowlol/bw_plex bw_plex --url=http://192.168.0.21:32400 --token=XXX watch` Managed to get it running like this.

**Comment by Hellowlol** [comment]
The only hard requirement is memory at it will crash. To be safe you should have 4 gb available. As for the cpu faster is better but it will work with anything if you use it on, but it will be painfully slow. Dunno about storage, that depends on any many entries in the db. (Downloads the theme songs)

I’m working on on another tool to find the intros it that pans out bw_plex will be a lot more light weight.
