### ISSUE TITLE
Youtube_DL possibly out of date

### ISSUE THREAD

**Issue by CDeLeon94** [Hellowlol/bw_plex#91]
Errors seen below seem to be resolved in an updated version of YoutubeDL: 
https://github.com/ytdl-org/youtube-dl/issues/21506

``` 
2019-06-29 08:44:44,530 :: bw_plex :: DEBUG :: plex.py:1154 :: Real Time with Bill Maher S17 E21 was added to UnRaid
2019-06-29 08:44:47,858 :: bw_plex :: DEBUG :: misc.py:695 :: Real Time with Bill Maher has 0 themes
2019-06-29 08:44:47,860 :: bw_plex :: DEBUG :: plex.py:111 :: downloading theme from process_to_db
2019-06-29 08:44:47,862 :: bw_plex :: DEBUG :: misc.py:454 :: Searching search_tunes for Real Time with Bill Maher using rk 29
2019-06-29 08:44:48,686 :: bw_plex :: DEBUG :: misc.py:469 :: http://www.televisiontunes.com/search.php?q=Real+Time+with+Bill+Maher
2019-06-29 08:44:48,779 :: bw_plex :: DEBUG :: misc.py:504 :: Searching youtube for name Real Time with Bill Maher rk 29 save_path /config/themes url None
2019-06-29 08:44:51,825 :: bw_plex :: ERROR :: YoutubeDL.py:520 :: ERROR: G92AB8ZG7xY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

2019-06-29 08:44:51,825 :: bw_plex :: ERROR :: misc.py:560 :: Failed to download theme song Real Time with Bill Maher

Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
ie_result = ie.extract(url)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 522, in extract
ie_result = self._real_extract(url)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1692, in _real_extract
video_id=video_id)
youtube_dl.utils.ExtractorError: G92AB8ZG7xY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/bw_plex/bw_plex/misc.py", line 556, in search_for_theme_youtube
ydl.download([name + ' theme song'])
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 2006, in download
url, force_generic_extractor=self.params.get('force_generic_extractor', False))
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 805, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 866, in process_ie_result
extra_info=extra_info)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 805, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 1004, in process_ie_result
extra_info=extra)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 866, in process_ie_result
extra_info=extra_info)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 817, in extract_info
self.report_error(compat_str(e), e.format_traceback())
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 622, in report_error
self.trouble(error_message, tb)
File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 592, in trouble
raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: G92AB8ZG7xY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

2019-06-29 08:44:51,826 :: bw_plex :: DEBUG :: misc.py:620 :: Download theme using source http://192.168.0.5:32400/library/metadata/29/theme/1561217557?X-Plex-Token=<hidden>
2019-06-29 08:44:51,828 :: bw_plex :: DEBUG :: misc.py:381 :: calling ffmpeg with ffmpeg -i http://192.168.0.5:32400/library/metadata/29/theme/1561217557?X-Plex-Token=<hidden> -ac 1 -ar 11025 -acodec pcm_s16le /tmp/offset_abm1kuie.wav
2019-06-29 08:44:52,107 :: bw_plex :: DEBUG :: misc.py:400 :: Done converted and moved /config/themes/Real Time with Bill Maher__29__1561815891.wav to /config/themes
2019-06-29 08:44:52,635 :: bw_plex :: DEBUG :: plex.py:115 :: Started to process Real.Time.with.Bill.Maher.s17e21
2019-06-29 08:44:52,636 :: bw_plex :: DEBUG :: plex.py:841 :: Checking if we can reach Real.Time.with.Bill.Maher.s17e21 directly
2019-06-29 08:44:52,636 :: bw_plex :: WARNING :: plex.py:860 :: Downloading from pms..

2019-06-29 08:44:52,636 :: bw_plex :: DEBUG :: misc.py:381 :: calling ffmpeg with ffmpeg -i http://192.168.0.5:32400/library/parts/55905/1561815873/file.mkv?download=1&X-Plex-Token=<hidden> -ac 1 -ar 11025 -ss 0 -t 600 -acodec pcm_s16le /tmp/offset_dfspfw7z.wav
2019-06-29 08:45:21,074 :: bw_plex :: DEBUG :: misc.py:403 :: Done converting /tmp/offset_dfspfw7z.wav
2019-06-29 08:45:38,250 :: bw_plex :: DEBUG :: misc.py:180 :: Match 2 rank 1 aligntime -9766 theme song /config/themes/Real Time with Bill Maher__29__1561815891.wav started at 237.40081632653062 (03:57) in ended at 238.0045351473923 (03:58) match length 0.603718820861678 in the video. Video was found in theme 10.634739229024943 ended at 11.23845804988662 confidence 0.006273525721455458
2019-06-29 08:45:38,251 :: bw_plex :: DEBUG :: misc.py:186 :: Best match was /config/themes/Real Time with Bill Maher__29__1561815891.wav
2019-06-29 08:45:38,251 :: bw_plex :: DEBUG :: plex.py:841 :: Checking if we can reach Real.Time.with.Bill.Maher.s17e21 directly
2019-06-29 08:45:38,252 :: bw_plex :: WARNING :: plex.py:860 :: Downloading from pms..

2019-06-29 08:45:38,252 :: bw_plex :: DEBUG :: misc.py:283 :: Calling find_offset_ffmpeg with command ffmpeg -i http://192.168.0.5:32400/library/parts/55905/1561815873/file.mkv?download=1&X-Plex-Token=<hidden> -t 600 -vf blackdetect=d=0.5:pix_th=0.1 -af silencedetect=n=-50dB:d=0.3 -f null -
2019-06-29 08:46:04,252 :: bw_plex :: DEBUG :: misc.py:218 :: final_video []
2019-06-29 08:46:04,252 :: bw_plex :: DEBUG :: misc.py:219 :: final_audio [['00:04', '00:05', '00:00']]
2019-06-29 08:46:04,253 :: bw_plex :: DEBUG :: misc.py:221 :: fin v []
2019-06-29 08:46:04,253 :: bw_plex :: DEBUG :: misc.py:222 :: fin a [[4.92483, 5.41683, 0.492]]
2019-06-29 08:46:04,254 :: bw_plex :: DEBUG :: misc.py:794 :: Checking if Real.Time.with.Bill.Maher.s17e21 has a recap with phrase previously on, last season, last episode using subtitles
2019-06-29 08:46:04,274 :: bw_plex :: DEBUG :: misc.py:733 :: Downloading subtitle from PMS
2019-06-29 08:46:05,104 :: bw_plex :: DEBUG :: plex.py:841 :: Checking if we can reach Real.Time.with.Bill.Maher.s17e21 directly
2019-06-29 08:46:05,104 :: bw_plex :: WARNING :: plex.py:860 :: Downloading from pms..
```

**Comment by Hellowlol** [comment]
I havnt pinned any YouTubedl version so it should grab the latest one as long as it’s not already is installed. What version have you installed?

**Comment by CDeLeon94** [comment]
In Docker on my Unraid server, appears to have been using a previous youtube_dl install versioned `2019.03.09`.
Opened a console within the docker and issued 
`pip3 install youtube_dl --upgrade`

now on version `2019.6.27`

No longer getting the error.

**Comment by Hellowlol** [comment]
Nice, let me know if any more issues appear. I need as many testers as possible.

**Comment by stickystyle** [comment]
FYI, for future searchers...the issue here is that the container built on docker hub is from 4 months ago [1]. Building the container locally will pull down the latest versions of the packages at build time. Dockerhub used to have a feature where you could trigger your autobuilds from commits in other repos (i.e. dependencies like youtube-dl), but that feature doesn't seem to exist anymore 🤷‍♂ 

[1] https://hub.docker.com/r/hellowlol/bw_plex/builds

**Comment by Hellowlol** [comment]
Thanks @stickystyle i didnt know. I just assumed I made a new build for each commit. I’m such a docker noob. If you have any tips feel free to make a pr.

**Comment by Hellowlol** [comment]
Autobuild should work in the future. New image is out.
