### ISSUE TITLE
Doesnt work with LG TV App?

### ISSUE THREAD

**Issue by dcplaya** [Hellowlol/bw_plex#94]
Set this up in Docker using the latest. I have an LG TV and I get this when it tries to skip.

```
2019-07-13 17:04:18,517 :: bw_plex :: DEBUG :: plex.py:1180 :: Called jump with South.Park.s16e05 20 30.55746031746032 None
2019-07-13 17:04:18,518 :: bw_plex :: INFO :: plex.py:934 :: Called client_action with 30.55746031746032 00:30 20 None
2019-07-13 17:04:18,537 :: bw_plex :: INFO :: plex.py:967 :: sessionkey 20 media_sessionkey 20
2019-07-13 17:04:18,537 :: bw_plex :: INFO :: plex.py:971 :: client LG OLED55B7A-U 1.0
2019-07-13 17:04:18,537 :: bw_plex :: INFO :: plex.py:1003 :: Checking if we cant find the correct client
2019-07-13 17:04:18,537 :: bw_plex :: DEBUG :: plex.py:1014 :: We couldnt match the client. Trying a hail marry.
2019-07-13 17:04:18,538 :: bw_plex :: INFO :: plex.py:1019 :: Connectiong to LG OLED55B7A-U
2019-07-13 17:04:18,538 :: bw_plex :: ERROR :: plex.py:85 :: There was an exception in client_action
Traceback (most recent call last):
  File "/app/bw_plex/bw_plex/plex.py", line 80, in inner
    return func(*args)
  File "/app/bw_plex/bw_plex/plex.py", line 1020, in client_action
    correct_client.connect()
  File "/usr/local/lib/python3.6/dist-packages/plexapi/client.py", line 91, in connect
    data = self.query(self.key, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/plexapi/client.py", line 155, in query
    url = self.url(path)
  File "/usr/local/lib/python3.6/dist-packages/plexapi/client.py", line 201, in url
    raise BadRequest('PlexClient object missing baseurl.')
plexapi.exceptions.BadRequest: PlexClient object missing baseurl.
2019-07-13 17:04:27,012 :: bw_plex :: DEBUG :: plex.py:1193 :: Found South.Park.s16e05 theme start 00:06, theme end 00:30, ffmpeg_end 00:33 progress 00:09 best_time 00:30 credits_start 00:00 credits_end 00:00
```

**Comment by Hellowlol** [comment]
Dunno, i dont have a lg to test with. Can you try to use plexapi to control the lg?

**Comment by Hellowlol** [comment]
I tried to add a fix for the traceback you got but i dunno if it works. A new dockerbuild should be ready in a half hour.

**Comment by dcplaya** [comment]
Ok, ill try it then.

Is there an easy way to check if the LG webOS app supports plexapi?

**Comment by Hellowlol** [comment]
I dont think it will work then. Can you control the client using the mobile app?

**Comment by dcplaya** [comment]
Dang!

Well if you want, you can add my docker-compose.yml file I used to create it. You didnt have one, as far as I could tell.

```
version: '3'

services:
  bw_plex:
    image: hellowlol/bw_plex:latest
    container_name: bw_plex
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
# Replace with your Plex library path
      - /mnt/unionfs/Media:/mnt/unionfs/Media
    environment:
      - url=**YOURE_URL**
      - token:**PLEX_TOKEN**
      - TZ=America/Los_Angeles
    command: bash -c "bw_plex --url **YOURE_URL** -t **PLEX_TOKEN** -df /config watch"
```

**Comment by Hellowlol** [comment]
Did you get it to work on the lg? I dont, send a PR :)

**Comment by dcplaya** [comment]
PR Sent.
I can't control the LG WebOS app from my phone. I don't think any TV app can be used unfortunately.
